version: '3.8'

services:
  streamlit-gpt4o:
    build: .
    ports:
      - "8501:7860"
    command: [
      "streamlit", "run",
      "/home/appuser/streamlit-gpt4o/app.py",
      "--server.port", "7860",
      "--server.address", "0.0.0.0"
    ]
